---
# This CloudFormation template defines the resources required to set up an Amazon 
# RDS (Relational Database Service) instance. It includes configurations for the database
# instance, such as instance type, storage, security groups, and other necessary parameters.
# The template will output two values: the ARN of the secret containing the database admin, 
# and the security group ID that clients should use to connect to the database.
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating an RDS instance with PostgreSQL engine."

Parameters:
  VpcId:
    Description: "VPC Id where the RDS instance will be created."
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: "Comma separated list of subnet ids where the RDS instance will be created."
    Type: List<AWS::EC2::Subnet::Id>

  DBAllocatedStorage:
    Description: "The size of the database (in GB)."
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 16384

  DBInstanceClass:
    Description: "The compute and memory capacity of the DB instance, for example db.m5.large. "
    Type: String
    Default: "db.t3.micro"

  DBAdminUsername:
    Description: "The master user name for the DB instance ."
    Type: String
    Default: adminuser

  DBName:
    Description: "The name of the database to create when the DB instance is created. If this parameter is not specified, the default postgres database is created in the DB instance."
    Type: String
    Default: app
  
  EnvId:
    Description: "The environment id. This value will be used to tag and namespace the resources."
    Type: String

Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "/${EnvId}/DbAdminSecret"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBAdminUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true
      Tags:
        - Key: EnvId
          Value: !Ref EnvId

  SecretTargetAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      TargetId: !Ref DBInstance
      SecretId: !Ref "Secret"
      TargetType: "AWS::RDS::DBInstance"

  ClientSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Ref "AWS::StackName"
      VpcId: !Ref VpcId
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"

  DatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Ref "AWS::StackName"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref "ClientSecurityGroup"
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: !Ref "AWS::StackName"
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"

  DBInstance:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: "AWS::RDS::DBInstance"
    Properties:
      MasterUsername: !Ref DBAdminUsername
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref Secret,
            ":SecretString:password}}",
          ],
        ]
      AllocatedStorage: !Ref DBAllocatedStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      EnableIAMDatabaseAuthentication: true
      Engine: postgres
      EngineVersion: "16.4"
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"

Outputs:
  AdminSecretArn:
    Description: "The ARN of the secret of the database admin."
    Value: !Ref Secret


  ClientSecurityGroupId:
    Description: "The security group clients should use to connect to the db."
    Value: !Ref ClientSecurityGroup

